on : push
jobs : 
        first-job :
                runs-on : ubuntu-latest
                steps :
                        - run : node --version
                        - run : npm --version
                        - user : actions/checkout@v4
                        - run : node index.js